AWSTemplateFormatVersion: 2010-09-09
Description: Template to Create an S3 Bucket with versioning

Parameters:
  BucketName:
    Type: String
    Description: S3 Bucket Name
    Default: ""

Resources:
  S3Bucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Join ['-' [!Ref AWS::AccountId, !Ref BucketName, 'code-pipeline-artifact-bucket']]  
      VersioningConfiguration:
        Status: Enabled	

Outputs:
  ccStackArtifactBucket:
    Description: CodePipeline Artifact Bucket Name
    Value: !Ref BucketName
    Export:
      Name: ccStackArtifactBucket

