AWSTemplateFormatVersion: "2010-09-09"
Description: "Template to Create a sample DynamoDb table via CodePipeline"

Resources:
  myDynamoDBTable:
    Type: AWS::DynamoDB::Table
    Properties:
      AttributeDefinitions:
        -
          AttributeName: "Album"
          AttributeType: "S"
        - 
          AttributeName: "Artist"
          AttributeType: "S"
      TableName: "myTableName"